---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - "wordpress::firewall"
    attributes:
      wordpress:
        domain_current_site: "govlearn.dev"
      :deploy: []
